// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.login;

/// <summary>
/// Server list
/// </summary>
public partial class GameServers
{
    public byte Id { get; set; }

    public string Name { get; set; }

    public string Host { get; set; }

    public int Port { get; set; }

    public bool? Hidden { get; set; }
}