// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.login;

/// <summary>
/// Table containing SQL update script information
/// </summary>
public partial class Updates
{
    public string ScriptName { get; set; }

    public sbyte Installed { get; set; }

    public DateTime InstallDate { get; set; }

    public string LastError { get; set; }
}