// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.login;

/// <summary>
/// Account login information
/// </summary>
public partial class Users
{
    public uint Id { get; set; }

    public string Username { get; set; }

    /// <summary>
    /// Hashed password of the user
    /// </summary>
    public string Password { get; set; }

    public string Email { get; set; }

    public ulong LastLogin { get; set; }

    public string LastIp { get; set; }

    public ulong CreatedAt { get; set; }

    public ulong UpdatedAt { get; set; }

    public uint Banned { get; set; }

    /// <summary>
    /// Ban reason to report back
    /// </summary>
    public uint BanReason { get; set; }
}