// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AAEmu.DBEditor.data.aaemu.game;

public partial class aaemu_game_context : DbContext
{
    public aaemu_game_context(DbContextOptions<aaemu_game_context> options)
        : base(options)
    {
    }

    public virtual DbSet<Abilities> Abilities { get; set; }

    public virtual DbSet<Accounts> Accounts { get; set; }

    public virtual DbSet<Actabilities> Actabilities { get; set; }

    public virtual DbSet<Appellations> Appellations { get; set; }

    public virtual DbSet<AuctionHouse> AuctionHouse { get; set; }

    public virtual DbSet<AuditIcsSales> AuditIcsSales { get; set; }

    public virtual DbSet<Blocked> Blocked { get; set; }

    public virtual DbSet<CashShopItem> CashShopItem { get; set; }

    public virtual DbSet<Characters> Characters { get; set; }

    public virtual DbSet<CompletedQuests> CompletedQuests { get; set; }

    public virtual DbSet<Doodads> Doodads { get; set; }

    public virtual DbSet<ExpeditionMembers> ExpeditionMembers { get; set; }

    public virtual DbSet<ExpeditionRolePolicies> ExpeditionRolePolicies { get; set; }

    public virtual DbSet<Expeditions> Expeditions { get; set; }

    public virtual DbSet<FamilyMembers> FamilyMembers { get; set; }

    public virtual DbSet<Friends> Friends { get; set; }

    public virtual DbSet<Housings> Housings { get; set; }

    public virtual DbSet<IcsMenu> IcsMenu { get; set; }

    public virtual DbSet<IcsShopItems> IcsShopItems { get; set; }

    public virtual DbSet<IcsSkus> IcsSkus { get; set; }

    public virtual DbSet<ItemContainers> ItemContainers { get; set; }

    public virtual DbSet<Items> Items { get; set; }

    public virtual DbSet<Mails> Mails { get; set; }

    public virtual DbSet<Mates> Mates { get; set; }

    public virtual DbSet<Music> Music { get; set; }

    public virtual DbSet<Options> Options { get; set; }

    public virtual DbSet<PortalBookCoords> PortalBookCoords { get; set; }

    public virtual DbSet<PortalVisitedDistrict> PortalVisitedDistrict { get; set; }

    public virtual DbSet<Quests> Quests { get; set; }

    public virtual DbSet<Skills> Skills { get; set; }

    public virtual DbSet<Slaves> Slaves { get; set; }

    public virtual DbSet<Uccs> Uccs { get; set; }

    public virtual DbSet<Updates> Updates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Abilities>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("abilities", tb => tb.HasComment("Skillsets Exp"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Exp)
                .HasColumnType("int(11)")
                .HasColumnName("exp");
        });

        modelBuilder.Entity<Accounts>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PRIMARY");

            entity
                .ToTable("accounts", tb => tb.HasComment("Account specific values not related to login"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.AccountId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("account_id");
            entity.Property(e => e.AccessLevel)
                .HasColumnType("int(11)")
                .HasColumnName("access_level");
            entity.Property(e => e.Credits)
                .HasColumnType("int(11)")
                .HasColumnName("credits");
            entity.Property(e => e.DivineClockTaken)
                .HasComment("Number of clicks taken today")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("divine_clock_taken");
            entity.Property(e => e.DivineClockTime)
                .HasComment("Time that has been passed already")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("divine_clock_time");
            entity.Property(e => e.Labor)
                .HasColumnType("int(11)")
                .HasColumnName("labor");
            entity.Property(e => e.LastCreditsTick)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_credits_tick");
            entity.Property(e => e.LastLaborTick)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_labor_tick");
            entity.Property(e => e.LastLogin)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_login");
            entity.Property(e => e.LastLoyaltyTick)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_loyalty_tick");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
            entity.Property(e => e.Loyalty)
                .HasColumnType("int(11)")
                .HasColumnName("loyalty");
        });

        modelBuilder.Entity<Actabilities>(entity =>
        {
            entity.HasKey(e => new { e.Owner, e.Id })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("actabilities", tb => tb.HasComment("Vocations"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Point)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("point");
            entity.Property(e => e.Step)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("step");
        });

        modelBuilder.Entity<Appellations>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("appellations", tb => tb.HasComment("Earned titles"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Active).HasColumnName("active");
        });

        modelBuilder.Entity<AuctionHouse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("auction_house", tb => tb.HasComment("Listed AH Items"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("bigint(20)")
                .HasColumnName("id");
            entity.Property(e => e.BidMoney)
                .HasColumnType("int(11)")
                .HasColumnName("bid_money");
            entity.Property(e => e.BidWorldId)
                .HasColumnType("int(11)")
                .HasColumnName("bid_world_id");
            entity.Property(e => e.BidderId)
                .HasColumnType("int(11)")
                .HasColumnName("bidder_id");
            entity.Property(e => e.BidderName)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("bidder_name")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.ClientId)
                .HasColumnType("int(11)")
                .HasColumnName("client_id");
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("client_name")
                .UseCollation("utf8mb4_general_ci")
                .HasCharSet("utf8mb4");
            entity.Property(e => e.DirectMoney)
                .HasColumnType("int(11)")
                .HasColumnName("direct_money");
            entity.Property(e => e.Duration)
                .HasColumnType("tinyint(4)")
                .HasColumnName("duration");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            entity.Property(e => e.Extra)
                .HasColumnType("int(11)")
                .HasColumnName("extra");
            entity.Property(e => e.ItemId)
                .HasColumnType("bigint(20)")
                .HasColumnName("item_id");
            entity.Property(e => e.PostDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("Time when the auction item was put up for sale (in UTC)")
                .HasColumnType("datetime")
                .HasColumnName("post_date");
            entity.Property(e => e.StackSize)
                .HasColumnType("int(11)")
                .HasColumnName("stack_size");
            entity.Property(e => e.StartMoney)
                .HasColumnType("int(11)")
                .HasColumnName("start_money");
            entity.Property(e => e.WorldId)
                .HasColumnType("tinyint(4)")
                .HasColumnName("world_id");
        });

        modelBuilder.Entity<AuditIcsSales>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("audit_ics_sales", tb => tb.HasComment("Sales history for the ICS"));

            entity.HasIndex(e => e.BuyerAccount, "buyer_account");

            entity.HasIndex(e => e.BuyerChar, "buyer_char");

            entity.HasIndex(e => e.TargetAccount, "target_account");

            entity.HasIndex(e => e.TargetChar, "target_char");

            entity.Property(e => e.Id)
                .HasColumnType("bigint(20) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.BuyerAccount)
                .HasComment("Account ID of the person buying this item")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("buyer_account");
            entity.Property(e => e.BuyerChar)
                .HasComment("Character that was logged in when buying")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("buyer_char");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasComment("Added description of this transaction")
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.SaleCost)
                .HasComment("Amount this item was sold for")
                .HasColumnType("int(11)")
                .HasColumnName("sale_cost");
            entity.Property(e => e.SaleCurrency)
                .HasComment("Which currency was used")
                .HasColumnType("tinyint(4) unsigned")
                .HasColumnName("sale_currency");
            entity.Property(e => e.SaleDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("Time of purchase (in UTC)")
                .HasColumnType("datetime")
                .HasColumnName("sale_date");
            entity.Property(e => e.ShopItemId)
                .HasComment("Shop item entry id of the sold item")
                .HasColumnType("int(11) unsigned")
                .HasColumnName("shop_item_id");
            entity.Property(e => e.Sku)
                .HasComment("SKU of the sold item")
                .HasColumnType("int(11) unsigned")
                .HasColumnName("sku");
            entity.Property(e => e.TargetAccount)
                .HasComment("Account of the person receiving the goods")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("target_account");
            entity.Property(e => e.TargetChar)
                .HasComment("Character that received the goods")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("target_char");
        });

        modelBuilder.Entity<Blocked>(entity =>
        {
            entity.HasKey(e => new { e.Owner, e.BlockedId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("blocked")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Owner)
                .HasColumnType("int(11)")
                .HasColumnName("owner");
            entity.Property(e => e.BlockedId)
                .HasColumnType("int(11)")
                .HasColumnName("blocked_id");
        });

        modelBuilder.Entity<CashShopItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("cash_shop_item", tb => tb.HasComment("此表来自于代码中的字段并去除重复字段生成。字段名称和内容以代码为准。"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasComment("shop_id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.BonusType)
                .HasDefaultValueSql("'0'")
                .HasComment("赠送类型")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("bonus_type");
            entity.Property(e => e.BounsCount)
                .HasDefaultValueSql("'0'")
                .HasComment("赠送数量")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("bouns_count");
            entity.Property(e => e.BuyCount)
                .HasDefaultValueSql("'0'")
                .HasColumnType("smallint(5) unsigned")
                .HasColumnName("buy_count");
            entity.Property(e => e.BuyId)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("buy_id");
            entity.Property(e => e.BuyType)
                .HasDefaultValueSql("'0'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("buy_type");
            entity.Property(e => e.CashName)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("出售名称")
                .HasColumnName("cash_name");
            entity.Property(e => e.CmdUi)
                .HasDefaultValueSql("'0'")
                .HasComment("是否限制一人一次")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("cmd_ui");
            entity.Property(e => e.DefaultFlag)
                .HasDefaultValueSql("'0'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("default_flag");
            entity.Property(e => e.DisPrice)
                .HasDefaultValueSql("'0'")
                .HasComment("当前售价")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("dis_price");
            entity.Property(e => e.EndDate)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasComment("出售截止")
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.EventDate)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasComment("活动时间")
                .HasColumnType("datetime")
                .HasColumnName("event_date");
            entity.Property(e => e.EventType)
                .HasDefaultValueSql("'0'")
                .HasComment("活动类型")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("event_type");
            entity.Property(e => e.IsHidden)
                .HasDefaultValueSql("'0'")
                .HasComment("是否隐藏")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("is_hidden");
            entity.Property(e => e.IsSell)
                .HasDefaultValueSql("'0'")
                .HasComment("是否出售")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("is_sell");
            entity.Property(e => e.ItemCount)
                .HasDefaultValueSql("'1'")
                .HasComment("捆绑数量")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_count");
            entity.Property(e => e.ItemTemplateId)
                .HasDefaultValueSql("'0'")
                .HasComment("物品模板id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_template_id");
            entity.Property(e => e.LevelMax)
                .HasDefaultValueSql("'0'")
                .HasComment("等级限制")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("level_max");
            entity.Property(e => e.LevelMin)
                .HasDefaultValueSql("'0'")
                .HasComment("等级限制")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("level_min");
            entity.Property(e => e.LimitType)
                .HasDefaultValueSql("'0'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("limit_type");
            entity.Property(e => e.MainTab)
                .HasDefaultValueSql("'1'")
                .HasComment("主分类1-6")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("main_tab");
            entity.Property(e => e.Price)
                .HasDefaultValueSql("'0'")
                .HasComment("价格")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("price");
            entity.Property(e => e.Remain)
                .HasDefaultValueSql("'0'")
                .HasComment("剩余数量")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("remain");
            entity.Property(e => e.SelectType)
                .HasDefaultValueSql("'0'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("select_type");
            entity.Property(e => e.StartDate)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasComment("出售开始")
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.SubTab)
                .HasDefaultValueSql("'1'")
                .HasComment("子分类1-7")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("sub_tab");
            entity.Property(e => e.Type)
                .HasDefaultValueSql("'0'")
                .HasComment("货币类型")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("type");
            entity.Property(e => e.UniqId)
                .HasDefaultValueSql("'0'")
                .HasComment("唯一ID")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("uniq_id");
        });

        modelBuilder.Entity<Characters>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.AccountId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("characters", tb => tb.HasComment("Basic player character data"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.AccountId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("account_id");
            entity.Property(e => e.Ability1)
                .HasColumnType("tinyint(4)")
                .HasColumnName("ability1");
            entity.Property(e => e.Ability2)
                .HasColumnType("tinyint(4)")
                .HasColumnName("ability2");
            entity.Property(e => e.Ability3)
                .HasColumnType("tinyint(4)")
                .HasColumnName("ability3");
            entity.Property(e => e.AccessLevel)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("access_level");
            entity.Property(e => e.AutoUseAapoint).HasColumnName("auto_use_aapoint");
            entity.Property(e => e.ConsumedLp)
                .HasColumnType("int(11)")
                .HasColumnName("consumed_lp");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CrimePoint)
                .HasColumnType("int(11)")
                .HasColumnName("crime_point");
            entity.Property(e => e.CrimeRecord)
                .HasColumnType("int(11)")
                .HasColumnName("crime_record");
            entity.Property(e => e.DeadCount)
                .HasColumnType("mediumint(8) unsigned")
                .HasColumnName("dead_count");
            entity.Property(e => e.DeadTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("dead_time");
            entity.Property(e => e.DeleteRequestTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("delete_request_time");
            entity.Property(e => e.DeleteTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("delete_time");
            entity.Property(e => e.Deleted)
                .HasColumnType("int(11)")
                .HasColumnName("deleted");
            entity.Property(e => e.ExpandedExpert)
                .HasColumnType("tinyint(4)")
                .HasColumnName("expanded_expert");
            entity.Property(e => e.ExpeditionId)
                .HasColumnType("int(11)")
                .HasColumnName("expedition_id");
            entity.Property(e => e.Experience)
                .HasColumnType("int(11)")
                .HasColumnName("experience");
            entity.Property(e => e.FactionId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("faction_id");
            entity.Property(e => e.FactionName)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("faction_name");
            entity.Property(e => e.Family)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("family");
            entity.Property(e => e.Gender)
                .HasColumnType("tinyint(4)")
                .HasColumnName("gender");
            entity.Property(e => e.Gift)
                .HasColumnType("int(11)")
                .HasColumnName("gift");
            entity.Property(e => e.HonorPoint)
                .HasColumnType("int(11)")
                .HasColumnName("honor_point");
            entity.Property(e => e.HostileFactionKills)
                .HasColumnType("int(11)")
                .HasColumnName("hostile_faction_kills");
            entity.Property(e => e.Hp)
                .HasColumnType("int(11)")
                .HasColumnName("hp");
            entity.Property(e => e.JuryPoint)
                .HasColumnType("int(11)")
                .HasColumnName("jury_point");
            entity.Property(e => e.LeaveTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("leave_time");
            entity.Property(e => e.Level)
                .HasColumnType("tinyint(4)")
                .HasColumnName("level");
            entity.Property(e => e.Money)
                .HasColumnType("bigint(20)")
                .HasColumnName("money");
            entity.Property(e => e.Money2)
                .HasColumnType("bigint(20)")
                .HasColumnName("money2");
            entity.Property(e => e.Mp)
                .HasColumnType("int(11)")
                .HasColumnName("mp");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.NumBankSlot)
                .HasDefaultValueSql("'50'")
                .HasColumnType("smallint(5) unsigned")
                .HasColumnName("num_bank_slot");
            entity.Property(e => e.NumInvSlot)
                .HasDefaultValueSql("'50'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("num_inv_slot");
            entity.Property(e => e.OnlineTime)
                .HasComment("Time that the character has been online")
                .HasColumnType("int(11)")
                .HasColumnName("online_time");
            entity.Property(e => e.Pitch).HasColumnName("pitch");
            entity.Property(e => e.Point)
                .HasColumnType("int(11)")
                .HasColumnName("point");
            entity.Property(e => e.PrevPoint)
                .HasColumnType("int(11)")
                .HasColumnName("prev_point");
            entity.Property(e => e.PvpHonor)
                .HasColumnType("int(11)")
                .HasColumnName("pvp_honor");
            entity.Property(e => e.Race)
                .HasColumnType("tinyint(4)")
                .HasColumnName("race");
            entity.Property(e => e.RecoverableExp)
                .HasColumnType("int(11)")
                .HasColumnName("recoverable_exp");
            entity.Property(e => e.ReturnDistrict)
                .HasColumnType("int(11)")
                .HasColumnName("return_district");
            entity.Property(e => e.RezPenaltyDuration)
                .HasColumnType("int(11)")
                .HasColumnName("rez_penalty_duration");
            entity.Property(e => e.RezTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("rez_time");
            entity.Property(e => e.RezWaitDuration)
                .HasColumnType("int(11)")
                .HasColumnName("rez_wait_duration");
            entity.Property(e => e.Roll).HasColumnName("roll");
            entity.Property(e => e.Slots)
                .IsRequired()
                .HasColumnType("blob")
                .HasColumnName("slots");
            entity.Property(e => e.TransferRequestTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("transfer_request_time");
            entity.Property(e => e.UnitModelParams)
                .IsRequired()
                .HasColumnType("blob")
                .HasColumnName("unit_model_params");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.VocationPoint)
                .HasColumnType("int(11)")
                .HasColumnName("vocation_point");
            entity.Property(e => e.WorldId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("world_id");
            entity.Property(e => e.X).HasColumnName("x");
            entity.Property(e => e.Y).HasColumnName("y");
            entity.Property(e => e.Yaw).HasColumnName("yaw");
            entity.Property(e => e.Z).HasColumnName("z");
            entity.Property(e => e.ZoneId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("zone_id");
        });

        modelBuilder.Entity<CompletedQuests>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("completed_quests", tb => tb.HasComment("Quests marked as completed for character"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnType("tinyblob")
                .HasColumnName("data");
        });

        modelBuilder.Entity<Doodads>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("doodads", tb => tb.HasComment("Persistent doodads (e.g. tradepacks, furniture)"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.AttachPoint)
                .HasDefaultValueSql("'0'")
                .HasComment("Slot this doodad fits in on the owner")
                .HasColumnType("int(11) unsigned")
                .HasColumnName("attach_point");
            entity.Property(e => e.CurrentPhaseId)
                .HasColumnType("int(11)")
                .HasColumnName("current_phase_id");
            entity.Property(e => e.Data)
                .HasComment("Doodad specific data")
                .HasColumnType("int(11)")
                .HasColumnName("data");
            entity.Property(e => e.FarmType)
                .HasDefaultValueSql("'0'")
                .HasComment("farm type for Public Farm")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("farm_type");
            entity.Property(e => e.GrowthTime)
                .HasColumnType("datetime")
                .HasColumnName("growth_time");
            entity.Property(e => e.HouseId)
                .HasComment("House DB Id if it is on actual house land")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("house_id");
            entity.Property(e => e.ItemContainerId)
                .HasComment("ItemContainer Id for Coffers")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_container_id");
            entity.Property(e => e.ItemId)
                .HasComment("Item DB Id of the associated item")
                .HasColumnType("bigint(20) unsigned")
                .HasColumnName("item_id");
            entity.Property(e => e.ItemTemplateId)
                .HasComment("ItemTemplateId of associated item")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_template_id");
            entity.Property(e => e.OwnerId)
                .HasComment("Character DB Id")
                .HasColumnType("int(11)")
                .HasColumnName("owner_id");
            entity.Property(e => e.OwnerType)
                .HasDefaultValueSql("'255'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("owner_type");
            entity.Property(e => e.ParentDoodad)
                .HasComment("doodads DB Id this object is standing on")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("parent_doodad");
            entity.Property(e => e.PhaseTime)
                .HasColumnType("datetime")
                .HasColumnName("phase_time");
            entity.Property(e => e.Pitch).HasColumnName("pitch");
            entity.Property(e => e.PlantTime)
                .HasColumnType("datetime")
                .HasColumnName("plant_time");
            entity.Property(e => e.Roll).HasColumnName("roll");
            entity.Property(e => e.Scale)
                .HasDefaultValueSql("'1'")
                .HasColumnName("scale");
            entity.Property(e => e.TemplateId)
                .HasColumnType("int(11)")
                .HasColumnName("template_id");
            entity.Property(e => e.X).HasColumnName("x");
            entity.Property(e => e.Y).HasColumnName("y");
            entity.Property(e => e.Yaw).HasColumnName("yaw");
            entity.Property(e => e.Z).HasColumnName("z");
        });

        modelBuilder.Entity<ExpeditionMembers>(entity =>
        {
            entity.HasKey(e => e.CharacterId).HasName("PRIMARY");

            entity
                .ToTable("expedition_members", tb => tb.HasComment("Guild members"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.CharacterId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("character_id");
            entity.Property(e => e.Ability1)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("ability1");
            entity.Property(e => e.Ability2)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("ability2");
            entity.Property(e => e.Ability3)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("ability3");
            entity.Property(e => e.ExpeditionId)
                .HasColumnType("int(11)")
                .HasColumnName("expedition_id");
            entity.Property(e => e.LastLeaveTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("last_leave_time");
            entity.Property(e => e.Level)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("level");
            entity.Property(e => e.Memo)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("memo");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Role)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("role");
        });

        modelBuilder.Entity<ExpeditionRolePolicies>(entity =>
        {
            entity.HasKey(e => new { e.ExpeditionId, e.Role })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("expedition_role_policies", tb => tb.HasComment("Guild role settings"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.ExpeditionId)
                .HasColumnType("int(11)")
                .HasColumnName("expedition_id");
            entity.Property(e => e.Role)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("role");
            entity.Property(e => e.Chat).HasColumnName("chat");
            entity.Property(e => e.Dismiss).HasColumnName("dismiss");
            entity.Property(e => e.DominionDeclare).HasColumnName("dominion_declare");
            entity.Property(e => e.Expel).HasColumnName("expel");
            entity.Property(e => e.Invite).HasColumnName("invite");
            entity.Property(e => e.JoinSiege).HasColumnName("join_siege");
            entity.Property(e => e.ManagerChat).HasColumnName("manager_chat");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Promote).HasColumnName("promote");
            entity.Property(e => e.SiegeMaster).HasColumnName("siege_master");
        });

        modelBuilder.Entity<Expeditions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("expeditions", tb => tb.HasComment("Guilds"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Mother)
                .HasColumnType("int(11)")
                .HasColumnName("mother");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Owner)
                .HasColumnType("int(11)")
                .HasColumnName("owner");
            entity.Property(e => e.OwnerName)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("owner_name");
        });

        modelBuilder.Entity<FamilyMembers>(entity =>
        {
            entity.HasKey(e => new { e.FamilyId, e.CharacterId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("family_members", tb => tb.HasComment("Family members"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.FamilyId)
                .HasColumnType("int(11)")
                .HasColumnName("family_id");
            entity.Property(e => e.CharacterId)
                .HasColumnType("int(11)")
                .HasColumnName("character_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("name");
            entity.Property(e => e.Role).HasColumnName("role");
            entity.Property(e => e.Title)
                .HasMaxLength(45)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Friends>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("friends", tb => tb.HasComment("Friendslist"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(11)")
                .HasColumnName("owner");
            entity.Property(e => e.FriendId)
                .HasColumnType("int(11)")
                .HasColumnName("friend_id");
        });

        modelBuilder.Entity<Housings>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("housings", tb => tb.HasComment("Player buildings"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.AccountId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("account_id");
            entity.Property(e => e.AllowRecover)
                .HasDefaultValueSql("'1'")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("allow_recover");
            entity.Property(e => e.CoOwner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("co_owner");
            entity.Property(e => e.CurrentAction)
                .HasColumnType("int(11)")
                .HasColumnName("current_action");
            entity.Property(e => e.CurrentStep)
                .HasColumnType("tinyint(4)")
                .HasColumnName("current_step");
            entity.Property(e => e.FactionId)
                .HasDefaultValueSql("'1'")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("faction_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Permission)
                .HasColumnType("tinyint(4)")
                .HasColumnName("permission");
            entity.Property(e => e.Pitch).HasColumnName("pitch");
            entity.Property(e => e.PlaceDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("place_date");
            entity.Property(e => e.ProtectedUntil)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("protected_until");
            entity.Property(e => e.Roll).HasColumnName("roll");
            entity.Property(e => e.SellPrice)
                .HasColumnType("bigint(20)")
                .HasColumnName("sell_price");
            entity.Property(e => e.SellTo)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("sell_to");
            entity.Property(e => e.TemplateId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("template_id");
            entity.Property(e => e.X).HasColumnName("x");
            entity.Property(e => e.Y).HasColumnName("y");
            entity.Property(e => e.Yaw).HasColumnName("yaw");
            entity.Property(e => e.Z).HasColumnName("z");
        });

        modelBuilder.Entity<IcsMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("ics_menu", tb => tb.HasComment("Contains what item will be displayed on which tab"));

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.MainTab)
                .HasDefaultValueSql("'1'")
                .HasComment("Which main tab to display on")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("main_tab");
            entity.Property(e => e.ShopId)
                .HasComment("Id of the item group for sale (shop item)")
                .HasColumnType("int(11) unsigned")
                .HasColumnName("shop_id");
            entity.Property(e => e.SubTab)
                .HasDefaultValueSql("'1'")
                .HasComment("Which sub tab to display on")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("sub_tab");
            entity.Property(e => e.TabPos)
                .HasComment("Used to change display order")
                .HasColumnType("int(11)")
                .HasColumnName("tab_pos");
        });

        modelBuilder.Entity<IcsShopItems>(entity =>
        {
            entity.HasKey(e => e.ShopId).HasName("PRIMARY");

            entity.ToTable("ics_shop_items", tb => tb.HasComment("Possible Item listings that are for sale"));

            entity.Property(e => e.ShopId)
                .HasComment("SKU item id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("shop_id");
            entity.Property(e => e.BuyRestrictId)
                .HasComment("Level or QuestId for restrict rule")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("buy_restrict_id");
            entity.Property(e => e.BuyRestrictType)
                .HasComment("Buy restriction rule, none (0), level (1) or quest(2)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("buy_restrict_type");
            entity.Property(e => e.DisplayItemId)
                .HasComment("Item who's icon to use for displaying in the shop, leave 0 for first item in the group")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("display_item_id");
            entity.Property(e => e.IsHidden)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("is_hidden");
            entity.Property(e => e.IsSale)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("is_sale");
            entity.Property(e => e.LevelMax)
                .HasComment("Maximum level to buy the item (does not show on UI)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("level_max");
            entity.Property(e => e.LevelMin)
                .HasComment("Minimum level to buy the item (does not show on UI)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("level_min");
            entity.Property(e => e.LimitedStockMax)
                .HasComment("Number of items left in stock for this SKU if limited stock is enabled")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("limited_stock_max");
            entity.Property(e => e.LimitedType)
                .HasComment("Enables limited stock mode if non-zero, Account(1), Chracter(2)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("limited_type");
            entity.Property(e => e.Name)
                .HasComment("Can be used to override the name in the shop")
                .HasColumnType("text")
                .HasColumnName("name");
            entity.Property(e => e.Remaining)
                .HasDefaultValueSql("'-1'")
                .HasComment("Number of items remaining, only for tab 1-1 (limited)")
                .HasColumnType("int(11)")
                .HasColumnName("remaining");
            entity.Property(e => e.SaleEnd)
                .HasComment("Limited sale end time")
                .HasColumnType("datetime")
                .HasColumnName("sale_end");
            entity.Property(e => e.SaleStart)
                .HasComment("Limited sale start time")
                .HasColumnType("datetime")
                .HasColumnName("sale_start");
            entity.Property(e => e.ShopButtons)
                .HasComment("All (0), NoCart (1), NoGift (2), OnlyBuy (3)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("shop_buttons");
        });

        modelBuilder.Entity<IcsSkus>(entity =>
        {
            entity.HasKey(e => e.Sku).HasName("PRIMARY");

            entity.ToTable("ics_skus", tb => tb.HasComment("Has the actual sales items for the details"));

            entity.Property(e => e.Sku)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("sku");
            entity.Property(e => e.BonusItemCount)
                .HasComment("Amount of bonus items included")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("bonus_item_count");
            entity.Property(e => e.BonusItemId)
                .HasComment("Bonus item included for this purchase")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("bonus_item_id");
            entity.Property(e => e.Currency)
                .HasComment("Credits(0), AAPoints(1), Loyalty(2), Coins(3)")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("currency");
            entity.Property(e => e.DiscountPrice)
                .HasComment("Discounted price (this is used if set)")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("discount_price");
            entity.Property(e => e.EventEndDate)
                .HasColumnType("datetime")
                .HasColumnName("event_end_date");
            entity.Property(e => e.EventType)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("event_type");
            entity.Property(e => e.IsDefault)
                .HasComment("Is this the default selection?")
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("is_default");
            entity.Property(e => e.ItemCount)
                .HasDefaultValueSql("'1'")
                .HasComment("Number of items for this detail")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_count");
            entity.Property(e => e.ItemId)
                .HasComment("Item that is for sale")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_id");
            entity.Property(e => e.Position)
                .HasComment("Used for display order inside the item details")
                .HasColumnType("int(10)")
                .HasColumnName("position");
            entity.Property(e => e.Price)
                .HasComment("Price of the item")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("price");
            entity.Property(e => e.SelectType)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("select_type");
            entity.Property(e => e.ShopId)
                .HasComment("Reference to the shop item")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("shop_id");
        });

        modelBuilder.Entity<ItemContainers>(entity =>
        {
            entity.HasKey(e => e.ContainerId).HasName("PRIMARY");

            entity
                .ToTable("item_containers")
                .UseCollation("utf8mb4_general_ci");

            entity.Property(e => e.ContainerId)
                .ValueGeneratedNever()
                .HasColumnType("int(10) unsigned")
                .HasColumnName("container_id");
            entity.Property(e => e.ContainerSize)
                .HasDefaultValueSql("'50'")
                .HasComment("Maximum Container Size")
                .HasColumnType("int(11)")
                .HasColumnName("container_size");
            entity.Property(e => e.ContainerType)
                .IsRequired()
                .HasMaxLength(64)
                .HasDefaultValueSql("'ItemContainer'")
                .HasComment("Partial Container Class Name")
                .HasColumnName("container_type");
            entity.Property(e => e.MateId)
                .HasComment("Owning Mate Id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("mate_id");
            entity.Property(e => e.OwnerId)
                .HasComment("Owning Character Id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner_id");
            entity.Property(e => e.SlotType)
                .HasComment("Internal Container Type")
                .HasColumnType("int(11)")
                .HasColumnName("slot_type");
        });

        modelBuilder.Entity<Items>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("items", tb => tb.HasComment("All items"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.HasIndex(e => e.Owner, "owner");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnType("bigint(20) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.ChargeCount)
                .HasComment("Number of charges left")
                .HasColumnType("int(11)")
                .HasColumnName("charge_count");
            entity.Property(e => e.ChargeTime)
                .HasComment("Time charged items got activated")
                .HasColumnType("datetime")
                .HasColumnName("charge_time");
            entity.Property(e => e.ContainerId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("container_id");
            entity.Property(e => e.Count)
                .HasColumnType("int(11)")
                .HasColumnName("count");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Details)
                .HasColumnType("blob")
                .HasColumnName("details");
            entity.Property(e => e.ExpireOnlineMinutes)
                .HasComment("Time left when player online")
                .HasColumnName("expire_online_minutes");
            entity.Property(e => e.ExpireTime)
                .HasComment("Fixed time expire")
                .HasColumnType("datetime")
                .HasColumnName("expire_time");
            entity.Property(e => e.Flags)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("flags");
            entity.Property(e => e.Grade)
                .HasDefaultValueSql("'0'")
                .HasColumnName("grade");
            entity.Property(e => e.LifespanMins)
                .HasColumnType("int(11)")
                .HasColumnName("lifespan_mins");
            entity.Property(e => e.MadeUnitId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("made_unit_id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Slot)
                .HasColumnType("int(11)")
                .HasColumnName("slot");
            entity.Property(e => e.SlotType)
                .HasComment("Internal Container Type")
                .HasColumnType("int(11)")
                .HasColumnName("slot_type");
            entity.Property(e => e.TemplateId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("template_id");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("type");
            entity.Property(e => e.Ucc)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("ucc");
            entity.Property(e => e.UnpackTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("unpack_time");
            entity.Property(e => e.UnsecureTime)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("unsecure_time");
        });

        modelBuilder.Entity<Mails>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("mails", tb => tb.HasComment("In-game mails"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Attachment0)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment0");
            entity.Property(e => e.Attachment1)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment1");
            entity.Property(e => e.Attachment2)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment2");
            entity.Property(e => e.Attachment3)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment3");
            entity.Property(e => e.Attachment4)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment4");
            entity.Property(e => e.Attachment5)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment5");
            entity.Property(e => e.Attachment6)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment6");
            entity.Property(e => e.Attachment7)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment7");
            entity.Property(e => e.Attachment8)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment8");
            entity.Property(e => e.Attachment9)
                .HasColumnType("bigint(20)")
                .HasColumnName("attachment9");
            entity.Property(e => e.AttachmentCount)
                .HasColumnType("int(11)")
                .HasColumnName("attachment_count");
            entity.Property(e => e.Extra)
                .HasColumnType("bigint(20)")
                .HasColumnName("extra");
            entity.Property(e => e.MoneyAmount1)
                .HasColumnType("int(11)")
                .HasColumnName("money_amount_1");
            entity.Property(e => e.MoneyAmount2)
                .HasColumnType("int(11)")
                .HasColumnName("money_amount_2");
            entity.Property(e => e.MoneyAmount3)
                .HasColumnType("int(11)")
                .HasColumnName("money_amount_3");
            entity.Property(e => e.OpenDate)
                .HasColumnType("datetime")
                .HasColumnName("open_date");
            entity.Property(e => e.ReceivedDate)
                .HasColumnType("datetime")
                .HasColumnName("received_date");
            entity.Property(e => e.ReceiverId)
                .HasColumnType("int(11)")
                .HasColumnName("receiver_id");
            entity.Property(e => e.ReceiverName)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("receiver_name");
            entity.Property(e => e.Returned)
                .HasColumnType("int(11)")
                .HasColumnName("returned");
            entity.Property(e => e.SendDate)
                .HasColumnType("datetime")
                .HasColumnName("send_date");
            entity.Property(e => e.SenderId)
                .HasColumnType("int(11)")
                .HasColumnName("sender_id");
            entity.Property(e => e.SenderName)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("sender_name");
            entity.Property(e => e.Status)
                .HasColumnType("int(11)")
                .HasColumnName("status");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("text");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasColumnType("int(11)")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Mates>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.ItemId, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

            entity
                .ToTable("mates", tb => tb.HasComment("Player mounts and pets"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.ItemId)
                .HasColumnType("bigint(20) unsigned")
                .HasColumnName("item_id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Hp)
                .HasColumnType("int(11)")
                .HasColumnName("hp");
            entity.Property(e => e.Level)
                .HasColumnType("tinyint(4)")
                .HasColumnName("level");
            entity.Property(e => e.Mileage)
                .HasColumnType("int(11)")
                .HasColumnName("mileage");
            entity.Property(e => e.Mp)
                .HasColumnType("int(11)")
                .HasColumnName("mp");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Xp)
                .HasColumnType("int(11)")
                .HasColumnName("xp");
        });

        modelBuilder.Entity<Music>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("music", tb => tb.HasComment("User Created Content (music)"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Author)
                .HasComment("PlayerId")
                .HasColumnType("int(11)")
                .HasColumnName("author");
            entity.Property(e => e.Song)
                .IsRequired()
                .HasComment("Song MML")
                .HasColumnType("text")
                .HasColumnName("song");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Options>(entity =>
        {
            entity.HasKey(e => new { e.Key, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("options", tb => tb.HasComment("Settings that the client stores on the server"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Key)
                .HasMaxLength(100)
                .HasColumnName("key");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("value");
        });

        modelBuilder.Entity<PortalBookCoords>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("portal_book_coords", tb => tb.HasComment("Recorded house portals in the portal book"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(11)")
                .HasColumnName("owner");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("name");
            entity.Property(e => e.SubZoneId)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("sub_zone_id");
            entity.Property(e => e.X)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("x");
            entity.Property(e => e.Y)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("y");
            entity.Property(e => e.Z)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("z");
            entity.Property(e => e.ZRot)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("z_rot");
            entity.Property(e => e.ZoneId)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("zone_id");
        });

        modelBuilder.Entity<PortalVisitedDistrict>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Subzone, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

            entity
                .ToTable("portal_visited_district", tb => tb.HasComment("List of visited area for the portal book"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Subzone)
                .HasColumnType("int(11)")
                .HasColumnName("subzone");
            entity.Property(e => e.Owner)
                .HasColumnType("int(11)")
                .HasColumnName("owner");
        });

        modelBuilder.Entity<Quests>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("quests", tb => tb.HasComment("Currently open quests"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnType("tinyblob")
                .HasColumnName("data");
            entity.Property(e => e.Status)
                .HasColumnType("tinyint(4)")
                .HasColumnName("status");
            entity.Property(e => e.TemplateId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("template_id");
        });

        modelBuilder.Entity<Skills>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Owner })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity
                .ToTable("skills", tb => tb.HasComment("Learned character skills"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.Owner)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner");
            entity.Property(e => e.Level)
                .HasColumnType("tinyint(4)")
                .HasColumnName("level");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("enum('Skill','Buff')")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Slaves>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("slaves", tb => tb.HasComment("Player vehicles summons"));

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnType("int(10) unsigned")
                .HasColumnName("id");
            entity.Property(e => e.AttachPoint)
                .HasDefaultValueSql("'0'")
                .HasComment("Binding point Id")
                .HasColumnType("int(10)")
                .HasColumnName("attach_point");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Hp)
                .HasColumnType("int(11)")
                .HasColumnName("hp");
            entity.Property(e => e.ItemId)
                .HasComment("Item that is used to summon this vehicle")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("item_id");
            entity.Property(e => e.Mp)
                .HasColumnType("int(11)")
                .HasColumnName("mp");
            entity.Property(e => e.Name)
                .HasColumnType("text")
                .HasColumnName("name");
            entity.Property(e => e.OwnerId)
                .HasDefaultValueSql("'0'")
                .HasComment("Parent unit DB Id")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner_id");
            entity.Property(e => e.OwnerType)
                .HasDefaultValueSql("'0'")
                .HasComment("Parent unit type")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("owner_type");
            entity.Property(e => e.Summoner)
                .HasComment("Owning player")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("summoner");
            entity.Property(e => e.TemplateId)
                .HasDefaultValueSql("'0'")
                .HasComment("Slave template Id of this vehicle")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("template_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.X).HasColumnName("x");
            entity.Property(e => e.Y).HasColumnName("y");
            entity.Property(e => e.Z).HasColumnName("z");
        });

        modelBuilder.Entity<Uccs>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("uccs", tb => tb.HasComment("User Created Content (crests)"))
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .HasColumnName("id");
            entity.Property(e => e.Color1B)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color1B");
            entity.Property(e => e.Color1G)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color1G");
            entity.Property(e => e.Color1R)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color1R");
            entity.Property(e => e.Color2B)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color2B");
            entity.Property(e => e.Color2G)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color2G");
            entity.Property(e => e.Color2R)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color2R");
            entity.Property(e => e.Color3B)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color3B");
            entity.Property(e => e.Color3G)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color3G");
            entity.Property(e => e.Color3R)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("color3R");
            entity.Property(e => e.Data)
                .HasComment("Raw uploaded UCC data")
                .HasColumnType("mediumblob")
                .HasColumnName("data");
            entity.Property(e => e.Modified)
                .HasDefaultValueSql("'0001-01-01 00:00:00'")
                .HasColumnType("datetime")
                .HasColumnName("modified");
            entity.Property(e => e.Pattern1)
                .HasComment("Background pattern")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("pattern1");
            entity.Property(e => e.Pattern2)
                .HasComment("Crest")
                .HasColumnType("int(10) unsigned")
                .HasColumnName("pattern2");
            entity.Property(e => e.Type)
                .HasColumnType("tinyint(4)")
                .HasColumnName("type");
            entity.Property(e => e.UploaderId)
                .HasComment("PlayerID")
                .HasColumnType("int(11)")
                .HasColumnName("uploader_id");
        });

        modelBuilder.Entity<Updates>(entity =>
        {
            entity.HasKey(e => e.ScriptName).HasName("PRIMARY");

            entity
                .ToTable("updates", tb => tb.HasComment("Table containing SQL update script information"))
                .UseCollation("utf8mb4_general_ci");

            entity.Property(e => e.ScriptName).HasColumnName("script_name");
            entity.Property(e => e.InstallDate)
                .HasColumnType("datetime")
                .HasColumnName("install_date");
            entity.Property(e => e.Installed)
                .HasColumnType("tinyint(4)")
                .HasColumnName("installed");
            entity.Property(e => e.LastError)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("last_error");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}