// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Account specific values not related to login
/// </summary>
public partial class Accounts
{
    public int AccountId { get; set; }

    public int Credits { get; set; }
}