// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Earned titles
/// </summary>
public partial class Appellations
{
    public uint Id { get; set; }

    public bool Active { get; set; }

    public uint Owner { get; set; }
}