// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Listed AH Items
/// </summary>
public partial class AuctionHouse
{
    public long Id { get; set; }

    public sbyte Duration { get; set; }

    public long ItemId { get; set; }

    /// <summary>
    /// Time when the auction item was put up for sale (in UTC)
    /// </summary>
    public DateTime PostDate { get; set; }

    public int StackSize { get; set; }

    public DateTime EndTime { get; set; }

    public sbyte WorldId { get; set; }

    public int ClientId { get; set; }

    public string ClientName { get; set; }

    public int StartMoney { get; set; }

    public int DirectMoney { get; set; }

    public int BidWorldId { get; set; }

    public int BidderId { get; set; }

    public string BidderName { get; set; }

    public int BidMoney { get; set; }

    public int Extra { get; set; }
}