// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

public partial class AuditCharSus
{
    public ulong Id { get; set; }

    /// <summary>
    /// Time of incident
    /// </summary>
    public DateTime? SusDate { get; set; }

    /// <summary>
    /// Category name for the activity
    /// </summary>
    public string SusCategory { get; set; }

    /// <summary>
    /// Involved account Id (if any)
    /// </summary>
    public uint? SusAccount { get; set; }

    /// <summary>
    /// Involved character Id (if any)
    /// </summary>
    public uint? SusCharacter { get; set; }

    public uint? ZoneGroup { get; set; }

    public float? X { get; set; }

    public float? Y { get; set; }

    public float? Z { get; set; }

    /// <summary>
    /// Description of the incident
    /// </summary>
    public string Description { get; set; }
}