// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Sales history for the ICS
/// </summary>
public partial class AuditIcsSales
{
    public ulong Id { get; set; }

    /// <summary>
    /// Account ID of the person buying this item
    /// </summary>
    public uint BuyerAccount { get; set; }

    /// <summary>
    /// Character that was logged in when buying
    /// </summary>
    public uint BuyerChar { get; set; }

    /// <summary>
    /// Account of the person receiving the goods
    /// </summary>
    public uint TargetAccount { get; set; }

    /// <summary>
    /// Character that received the goods
    /// </summary>
    public uint TargetChar { get; set; }

    /// <summary>
    /// Time of purchase (in UTC)
    /// </summary>
    public DateTime SaleDate { get; set; }

    /// <summary>
    /// Shop item entry id of the sold item
    /// </summary>
    public uint ShopItemId { get; set; }

    /// <summary>
    /// SKU of the sold item
    /// </summary>
    public uint Sku { get; set; }

    /// <summary>
    /// Amount this item was sold for
    /// </summary>
    public int SaleCost { get; set; }

    /// <summary>
    /// Which currency was used
    /// </summary>
    public byte SaleCurrency { get; set; }

    /// <summary>
    /// Added description of this transaction
    /// </summary>
    public string Description { get; set; }
}