// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

public partial class Blocked
{
    public int Owner { get; set; }

    public int BlockedId { get; set; }
}