// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Persistent doodads (e.g. tradepacks, furniture)
/// </summary>
public partial class Doodads
{
    public uint Id { get; set; }

    /// <summary>
    /// Character DB Id
    /// </summary>
    public int? OwnerId { get; set; }

    public byte? OwnerType { get; set; }

    /// <summary>
    /// Slot this doodad fits in on the owner
    /// </summary>
    public uint? AttachPoint { get; set; }

    public int TemplateId { get; set; }

    public int CurrentPhaseId { get; set; }

    public DateTime PlantTime { get; set; }

    public DateTime GrowthTime { get; set; }

    public DateTime PhaseTime { get; set; }

    public float X { get; set; }

    public float Y { get; set; }

    public float Z { get; set; }

    public float Roll { get; set; }

    public float Pitch { get; set; }

    public float Yaw { get; set; }

    public float Scale { get; set; }

    /// <summary>
    /// Item DB Id of the associated item
    /// </summary>
    public ulong ItemId { get; set; }

    /// <summary>
    /// House DB Id if it is on actual house land
    /// </summary>
    public uint HouseId { get; set; }

    /// <summary>
    /// doodads DB Id this object is standing on
    /// </summary>
    public uint ParentDoodad { get; set; }

    /// <summary>
    /// ItemTemplateId of associated item
    /// </summary>
    public uint ItemTemplateId { get; set; }

    /// <summary>
    /// ItemContainer Id for Coffers
    /// </summary>
    public uint ItemContainerId { get; set; }

    /// <summary>
    /// Doodad specific data
    /// </summary>
    public int Data { get; set; }

    /// <summary>
    /// farm type for Public Farm
    /// </summary>
    public uint? FarmType { get; set; }
}