// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Family members
/// </summary>
public partial class FamilyMembers
{
    public int CharacterId { get; set; }

    public int FamilyId { get; set; }

    public string Name { get; set; }

    public bool Role { get; set; }

    public string Title { get; set; }
}