// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Friendslist
/// </summary>
public partial class Friends
{
    public int Id { get; set; }

    public int FriendId { get; set; }

    public int Owner { get; set; }
}