// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Contains what item will be displayed on which tab
/// </summary>
public partial class IcsMenu
{
    public int Id { get; set; }

    /// <summary>
    /// Which main tab to display on
    /// </summary>
    public byte MainTab { get; set; }

    /// <summary>
    /// Which sub tab to display on
    /// </summary>
    public byte SubTab { get; set; }

    /// <summary>
    /// Used to change display order
    /// </summary>
    public int TabPos { get; set; }

    /// <summary>
    /// Id of the item group for sale (shop item)
    /// </summary>
    public uint ShopId { get; set; }
}