// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Has the actual sales items for the details
/// </summary>
public partial class IcsSkus
{
    public uint Sku { get; set; }

    /// <summary>
    /// Reference to the shop item
    /// </summary>
    public uint ShopId { get; set; }

    /// <summary>
    /// Used for display order inside the item details
    /// </summary>
    public int Position { get; set; }

    /// <summary>
    /// Item that is for sale
    /// </summary>
    public uint ItemId { get; set; }

    /// <summary>
    /// Number of items for this detail
    /// </summary>
    public uint ItemCount { get; set; }

    public byte SelectType { get; set; }

    /// <summary>
    /// Is this the default selection?
    /// </summary>
    public byte IsDefault { get; set; }

    public byte EventType { get; set; }

    public DateTime? EventEndDate { get; set; }

    /// <summary>
    /// Credits(0), AAPoints(1), Loyalty(2), Coins(3)
    /// </summary>
    public byte Currency { get; set; }

    /// <summary>
    /// Price of the item
    /// </summary>
    public uint Price { get; set; }

    /// <summary>
    /// Discounted price (this is used if set)
    /// </summary>
    public uint DiscountPrice { get; set; }

    /// <summary>
    /// Bonus item included for this purchase
    /// </summary>
    public uint BonusItemId { get; set; }

    /// <summary>
    /// Amount of bonus items included
    /// </summary>
    public uint BonusItemCount { get; set; }
}