// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

public partial class ItemContainers
{
    public uint ContainerId { get; set; }

    /// <summary>
    /// Partial Container Class Name
    /// </summary>
    public string ContainerType { get; set; }

    /// <summary>
    /// Maximum Container Size
    /// </summary>
    public int ContainerSize { get; set; }

    /// <summary>
    /// Owning Character Id
    /// </summary>
    public uint OwnerId { get; set; }

    /// <summary>
    /// Owning Mate Id
    /// </summary>
    public uint MateId { get; set; }

    /// <summary>
    /// Internal Container Type
    /// </summary>
    public int SlotType { get; set; }
}