// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// List of visited area for the portal book
/// </summary>
public partial class PortalVisitedDistrict
{
    public int Id { get; set; }

    public int Subzone { get; set; }

    public int Owner { get; set; }
}