// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Recorded house portals in the portal book
/// </summary>
public partial class PortalBookCoords
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? X { get; set; }

    public int? Y { get; set; }

    public int? Z { get; set; }

    public int? ZoneId { get; set; }

    public int? ZRot { get; set; }

    public int? SubZoneId { get; set; }

    public int Owner { get; set; }
}