// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu.game;

/// <summary>
/// Player vehicles summons
/// </summary>
public partial class Slaves
{
    public uint Id { get; set; }

    /// <summary>
    /// Item that is used to summon this vehicle
    /// </summary>
    public uint? ItemId { get; set; }

    public string Name { get; set; }

    public uint? Owner { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? Hp { get; set; }

    public int? Mp { get; set; }

    public float? X { get; set; }

    public float? Y { get; set; }

    public float? Z { get; set; }
}