// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu;

/// <summary>
/// Skillsets Exp
/// </summary>
public partial class Ability
{
    public byte Id { get; set; }

    public int Exp { get; set; }

    public uint Owner { get; set; }
}