// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu;

/// <summary>
/// Vocations
/// </summary>
public partial class Actability
{
    public uint Id { get; set; }

    public uint Point { get; set; }

    public byte Step { get; set; }

    public uint Owner { get; set; }
}