// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu;

/// <summary>
/// Quests marked as completed for character
/// </summary>
public partial class CompletedQuest
{
    public uint Id { get; set; }

    public byte[] Data { get; set; }

    public uint Owner { get; set; }
}