// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AAEmu.DBEditor.data.aaemu;

/// <summary>
/// Settings that the client stores on the server
/// </summary>
public partial class Option
{
    public string Key { get; set; }

    public string Value { get; set; }

    public uint Owner { get; set; }
}